name: Generate Pacman Game


on:

  schedule:
    - cron: "0 */24 * * *"

  workflow_dispatch:

  push:
    branches:
      - main



jobs:

  generate:

    permissions:
      contents: write

    runs-on: ubuntu-latest

    timeout-minutes: 20


    steps:

      - name: Generate pacman contribution graph

        uses: abozanona/pacman-contribution-graph@main

        with:

          github_user_name: ${{ github.repository_owner }}

          games: 'pacman,breakout,galaga,puzzle-bobble,bomberman'


      - name: Customize theme colors

        run: |

          mkdir -p dist


          sed -i \
          's/#161b22/#0A101F/g' \
          dist/*.svg


          sed -i \
          's/#39d353/#22D3EE/g' \
          dist/*.svg


          sed -i \
          's/#26a641/#7C3AED/g' \
          dist/*.svg


          sed -i \
          's/#0e4429/#A78BFA/g' \
          dist/*.svg


      - name: Push pacman animation

        uses: crazy-max/ghaction-github-pages@v3.1.0

        with:

          target_branch: output

          build_dir: dist

          commit_message: "Update pacman animation [skip ci]"


        env:

          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
